/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ETProxy */

#ifndef _Included_ETProxy
#define _Included_ETProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ETProxy
 * Method:    getObjectSize
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ETProxy_getObjectSize
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
